services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    networks:
      - project_review_default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - PG_HOST=postgres
      - PG_USER=root
      - PG_PASSWORD=root_password
      - PG_DB=products_db
    depends_on:
      - postgres
    networks:
      - project_review_default
    ports:
      - "5000:5000"
    command: ["sh", "-c", "sleep 10 && python app.py"]

networks:
  project_review_default:

volumes:
  postgres_data:
